### ISSUE TITLE
Executable is being detected as virus with Windows Defender. [Trojan:Win32/Wacatac.DB!ml]

### ISSUE THREAD

**Issue by RomnKo** [samclane/LIFX-Control-Panel#105] opened 2020-10-09 21:37 UTC
**Describe the bug**
Executable is being detected as virus with Windows Defender. [Trojan:Win32/Wacatac.DB!ml]

**To Reproduce**
    1. Windows Defender automatically detects the release executable as a virus.

**Expected behavior**
    Shouldn't be detected as a virus...

**Screenshots**
![image](https://user-images.githubusercontent.com/1963962/95633339-54aef600-0a3c-11eb-9632-988d4b9ebbb6.png)

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: 1.8.0 from Releases page
 - OS: Windows 10, 20H2 (19042.546)

**Additional context**
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.DB!ml&threatid=2147757790

Windows Defender didn't flag previous 1.7.6 release.

**Comment by jmwarren85** [comment] 2020-12-05 04:11
Having the same issues  on the same LIFX Control panel build and Windows 10 20H2 build 19042.630

**Comment by Josephur** [comment] 2020-12-17 02:29
The executable was fine weeks ago but now Windows Defender is flagging  it again.

**Comment by samclane** [comment] 2021-12-06 17:13
Duplicate of #39

**Closed by samclane** 2021-12-06 17:13 UTC
Labels: bug, help wanted
